language: cpp
sudo: false
dist: bionic

cache:
  ccache: true
  directories:
    - $HOME/cmake
    - $HOME/deps

before_script:
  - bash ./scripts/travis/install_deps.sh $HOME/deps
  - rm -rf $HOME/deps/source # delete downloaded sources to minimize cache size

script:
  - cmake -version
  - mkdir _build
  - cd _build
  - bash ../scripts/travis/cmake.sh $HOME/deps
  - ninja publish
  - ninja -j 8
  - ctest

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - ninja-build
            - gcc-9
            - g++-9
            - libgflags-dev
            - libsnappy-dev
      env:
        - BOOST_ROOT="$HOME/deps/boost"
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

  # include:
  #   - os: linux
  #     addons:
  #       apt:
  #         update: true
  #         sources:
  #           - sourceline: 'ppa:ubuntu-toolchain-r/test'
  #         packages:
  #           - ninja-build
  #           - gcc-8
  #           - g++-8
  #           - libgflags-dev
  #           - libsnappy-dev
  #     env:
  #       - BOOST_ROOT="$HOME/deps/boost"
  #       - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-8
    #   env:
    #     - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-9
    #   env:
    #     - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

before_install:
  - bash ./scripts/travis/install_cmake.sh $HOME/cmake
  - export PATH="$HOME/cmake/bin:$PATH"
  - eval "${MATRIX_EVAL}"
